version: 2.1

orbs:
  node: circleci/node@5

jobs:
  test:
    docker:
      - image: mcr.microsoft.com/playwright:v1.52.0-jammy
    resource_class: medium
    steps:
      - checkout

        - run:
          name: Install dependencies
          command: |
          npm ci

        - run:
          name: Run API tests
          command: npm run test:api -- --reporter=list,junit

        - run:
          name: Run UI tests
          command: npm run test:ui -- --reporter=list,junit

      - store_artifacts:
          path: playwright-report
          destination: playwright-report

      - store_test_results:
          path: test-results

workflows:
  regression:
    jobs:
      - test
